# Generated by Django 5.2.17 on 2026-09-30 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_installation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_gid", models.CharField(help_text="Shopify product GID", max_length=255)),
                ("title", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("volume", "Volume"), ("bogo", "BOGO"), ("free_gift", "Free gift")],
                        default="volume",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="OfferConfig validated against apps.offers.schemas.OfferConfig"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("ended", "Ended")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, help_text="End time for countdown timer; None = no timer", null=True
                    ),
                ),
                ("show_timer", models.BooleanField(default=False, help_text="Show countdown timer in storefront")),
                ("discount_gid", models.CharField(blank=True, default="", max_length=255)),
                ("offer_display_metaobject_gid", models.CharField(blank=True, default="", max_length=255)),
                ("product_metafield_gid", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("show_timer", False), ("ends_at__isnull", False), _connector="OR"),
                        name="offer_timer_requires_ends_at",
                    )
                ],
            },
        ),
    ]
