# Generated by Django 5.2.17 on 2026-09-30 14:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_installation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("store", "Store"), ("page", "Page")], max_length=10)),
                (
                    "page_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdp", "PDP"),
                            ("landing", "Landing"),
                            ("advertorial", "Advertorial"),
                            ("listicle", "Listicle"),
                            ("home", "Home"),
                            ("about", "About"),
                        ],
                        help_text="Null only for kind=store",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("content_locale", models.CharField(max_length=5)),
                ("input", models.JSONField(help_text="JobInput.model_dump(mode='json')")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("needs_input", "Needs input"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=15,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("import", "Import"),
                            ("research", "Research"),
                            ("copy", "Copy"),
                            ("images", "Images"),
                            ("compliance_check", "Compliance check"),
                            ("layout", "Layout"),
                            ("publish", "Publish"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=60, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("ai_cost_usd", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Unique per shop; prevents duplicate jobs on double-click", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="For kind=store: child jobs (home, pdp, about) reference the store job",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="generator.generationjob",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="core.shop"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobStep",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("research", "Research"),
                            ("copy", "Copy"),
                            ("images", "Images"),
                            ("compliance_check", "Compliance check"),
                            ("layout", "Layout"),
                            ("publish", "Publish"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("attempt", models.PositiveSmallIntegerField(default=0)),
                ("output", models.JSONField(blank=True, help_text="Validated output checkpoint", null=True)),
                ("ai_cost_usd", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="generator.generationjob"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiCall",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("research", "Research"),
                            ("copy", "Copy"),
                            ("image", "Image"),
                            ("fidelity", "Fidelity"),
                            ("compliance", "Compliance"),
                            ("url_facts", "URL facts"),
                            ("palette", "Palette"),
                            ("rewrite", "Rewrite"),
                            ("translate", "Translate"),
                            ("shot_plan", "Shot plan"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("anthropic", "Anthropic"), ("vertex", "Vertex AI"), ("openai", "OpenAI")],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=80)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("images", models.PositiveSmallIntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=4, max_digits=10)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        help_text="CASCADE; also for calls outside a job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_calls",
                        to="core.shop",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for palette, rewrite, translate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_calls",
                        to="generator.jobstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("pdp", "PDP"),
                            ("landing", "Landing"),
                            ("advertorial", "Advertorial"),
                            ("listicle", "Listicle"),
                            ("home", "Home"),
                            ("about", "About"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Internal and Shopify page title", max_length=120)),
                ("angle", models.CharField(blank=True, help_text="Chosen angle", max_length=120)),
                ("content_locale", models.CharField(max_length=5)),
                (
                    "sections",
                    models.JSONField(
                        default=dict, help_text='SectionsPayload per language: {"nl": {...}, "de": {...}}'
                    ),
                ),
                (
                    "images",
                    models.JSONField(
                        default=dict, help_text='{"hero": "gid://shopify/MediaImage/…", "lifestyle_1": …}'
                    ),
                ),
                ("seo_title", models.CharField(blank=True, max_length=60)),
                ("seo_description", models.CharField(blank=True, max_length=155)),
                ("ai_image_disclosure", models.BooleanField(default=True)),
                ("product_gid", models.CharField(blank=True, max_length=255, null=True)),
                ("shopify_page_gid", models.CharField(blank=True, max_length=255, null=True)),
                ("shopify_page_handle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "metaobject_handles",
                    models.JSONField(default=dict, help_text='Per language: {"nl": "mq-<short>-<uuid8>-nl"}'),
                ),
                ("metaobject_gids", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("live", "Live"), ("archived", "Archived")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("compliance_score", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="generator.generationjob",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="core.shop"
                    ),
                ),
                (
                    "variant_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="For A/B in v1.1",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="generator.page",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(fields=["shop", "status"], name="generator_g_shop_id_e77629_idx"),
        ),
        migrations.AddConstraint(
            model_name="generationjob",
            constraint=models.UniqueConstraint(
                fields=("shop", "idempotency_key"), name="unique_job_idempotency_per_shop"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobstep",
            constraint=models.UniqueConstraint(fields=("job", "name"), name="unique_job_step_name"),
        ),
        migrations.AddIndex(
            model_name="aicall",
            index=models.Index(fields=["shop", "purpose"], name="generator_a_shop_id_1ecfc9_idx"),
        ),
        migrations.AddIndex(
            model_name="aicall",
            index=models.Index(fields=["shop", "created_at"], name="generator_a_shop_id_c0f911_idx"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["shop", "status"], name="generator_p_shop_id_ea672f_idx"),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["shop", "product_gid"], name="generator_p_shop_id_21efe5_idx"),
        ),
    ]
