# Generated by Django 5.2.17 on 2026-10-02 05:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shop_onboarding_route'),
        ('generator', '0001_add_pipeline_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onboarding_route', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('brief', 'Brief'), ('names', 'Names'), ('brand', 'Brand'), ('ideas', 'Product ideas'), ('structure', 'Store structure'), ('building', 'Building'), ('done', 'Done')], default='brief', max_length=16)),
                ('niche_hint', models.CharField(blank=True, default='', max_length=40)),
                ('free_text', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('markets', models.JSONField(blank=True, default=list)),
                ('content_locales', models.JSONField(blank=True, default=list)),
                ('audience', models.CharField(blank=True, default='', max_length=200)),
                ('price_level', models.CharField(blank=True, default='', max_length=16)),
                ('import_app', models.CharField(blank=True, default='', max_length=16)),
                ('niche_slug', models.CharField(blank=True, default='', max_length=80)),
                ('name_suggestions', models.JSONField(blank=True, default=list)),
                ('regenerate_count', models.IntegerField(default=0)),
                ('brand_name', models.CharField(blank=True, default='', max_length=40)),
                ('brand_slug', models.CharField(blank=True, default='', max_length=80)),
                ('logo_concept', models.JSONField(blank=True, null=True)),
                ('palette', models.JSONField(blank=True, null=True)),
                ('fonts', models.JSONField(blank=True, null=True)),
                ('store_structure', models.JSONField(blank=True, null=True)),
                ('product_ideas', models.JSONField(blank=True, null=True)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_blueprints', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'status'], name='generator_s_shop_id_a1625f_idx')],
            },
        ),
    ]
