# Generated by Django 5.2.17 on 2026-10-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_storeblueprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeblueprint',
            name='brand_proposal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
