# Generated by Django 5.2.17 on 2026-10-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_storeblueprint_brand_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeblueprint',
            name='selected_product_gids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storeblueprint',
            name='started_products_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
