# Generated by Django 5.2.17 on 2026-10-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_storeblueprint_selected_product_gids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeblueprint',
            name='imported_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
