# Generated by Django 5.2.17 on 2026-10-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_storeblueprint_imported_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeblueprint',
            name='structure_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
