# Generated by Django 5.2.17 on 2026-10-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_storeblueprint_structure_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeblueprint',
            name='standard_pages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='page_type',
            field=models.CharField(blank=True, choices=[('pdp', 'PDP'), ('landing', 'Landing'), ('advertorial', 'Advertorial'), ('listicle', 'Listicle'), ('home', 'Home'), ('about', 'About'), ('faq', 'FAQ'), ('shipping', 'Shipping'), ('returns', 'Returns')], help_text='Null only for kind=store', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('pdp', 'PDP'), ('landing', 'Landing'), ('advertorial', 'Advertorial'), ('listicle', 'Listicle'), ('home', 'Home'), ('about', 'About'), ('faq', 'FAQ'), ('shipping', 'Shipping'), ('returns', 'Returns')], max_length=20),
        ),
    ]
