# Generated by Django 5.2.17 on 2026-10-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shop_onboarding_route'),
        ('generator', '0007_storeblueprint_standard_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeblueprint',
            name='build_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='generator.generationjob'),
        ),
        migrations.AddField(
            model_name='storeblueprint',
            name='store_limit_reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ManagedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('collection', 'Collection'), ('menu', 'Menu'), ('page', 'Page')], max_length=12)),
                ('gid', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_resources', to='generator.storeblueprint')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_resources', to='core.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop', 'gid'), name='unique_managed_resource_gid_per_shop')],
            },
        ),
    ]
