# Generated by Django 5.2.17 on 2026-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_storeblueprint_build_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeblueprint',
            name='menu_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeblueprint',
            name='publish_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
