# Generated by Django 5.2.17 on 2026-10-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_storeblueprint_menu_placed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='compliance_findings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
