# Generated by Django 5.2.17 on 2026-10-02 20:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_page_compliance_findings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicall',
            name='purpose',
            field=models.CharField(choices=[('research', 'Research'), ('copy', 'Copy'), ('image', 'Image'), ('fidelity', 'Fidelity'), ('compliance', 'Compliance'), ('url_facts', 'URL facts'), ('palette', 'Palette'), ('rewrite', 'Rewrite'), ('translate', 'Translate'), ('shot_plan', 'Shot plan'), ('edit', 'Page edit')], max_length=40),
        ),
        migrations.CreateModel(
            name='PageEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(max_length=5)),
                ('instruction', models.TextField()),
                ('scope_section_index', models.SmallIntegerField(blank=True, help_text='null = whole page', null=True)),
                ('operations', models.JSONField(default=list)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='proposed', max_length=10)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('base_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_edits', to='generator.aicall')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='generator.page')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page', 'status'], name='generator_p_page_id_35090a_idx')],
            },
        ),
    ]
