# Shopify Theme App Extension configuration
# See docs/04-extensions.md §1

api_version = "2026-07"

[[extensions]]
name = "Mosaiq"
handle = "mosaiq-theme-extension"
uid = "a4b1aa3f-1cef-c462-6df7-ebf70ca53ee3148fd78b"
type = "theme"
