# Generated by Django 5.2.17 on 2026-09-30 15:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_installation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "domain_sha256",
                    models.CharField(help_text="sha256 of the lowercase shop domain", max_length=64, unique=True),
                ),
                ("first_trial_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-first_trial_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "plan",
                    models.CharField(
                        choices=[("starter", "Starter"), ("pro", "Pro"), ("agency", "Agency")], max_length=20
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("every_30_days", "Every 30 days"), ("annual", "Annual")],
                        default="every_30_days",
                        max_length=20,
                    ),
                ),
                ("shopify_subscription_gid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("frozen", "Frozen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("test", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subscription", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageCounter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("period_start", models.DateField(help_text="Start of the 30-day period")),
                ("store_generations", models.PositiveIntegerField(default=0)),
                ("ai_images", models.PositiveIntegerField(default=0)),
                (
                    "reserved_store_generations",
                    models.PositiveIntegerField(
                        default=0, help_text="Reserved at job start, released on completion/failure"
                    ),
                ),
                (
                    "reserved_ai_images",
                    models.PositiveIntegerField(
                        default=0, help_text="Reserved at job start, released on completion/failure"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="usage_counters", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "indexes": [models.Index(fields=["shop", "period_start"], name="billing_usa_shop_id_52df03_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shop", "period_start"), name="unique_usage_counter_per_shop_period"
                    )
                ],
            },
        ),
    ]
