# Generated by Django 5.2.17 on 2026-10-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_add_billing_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagecounter',
            name='page_edits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
