# Generated by Django 5.2.17 on 2026-10-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_usagecounter_page_edits'),
        ('core', '0005_shop_onboarding_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundingDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_off', models.PositiveSmallIntegerField(default=50, help_text='e.g. 50 = 50% off')),
                ('valid_until', models.DateTimeField(help_text='Discount expires automatically after this date')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founding_discount', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
