# Generated by Django 5.2.17 on 2026-09-30 07:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("domain", models.CharField(help_text="*.myshopify.com, lowercase", max_length=255, unique=True)),
                ("shopify_gid", models.CharField(max_length=255, unique=True)),
                ("access_token_encrypted", models.BinaryField()),
                ("access_token_expires_at", models.DateTimeField()),
                ("refresh_token_encrypted", models.BinaryField()),
                ("refresh_token_expires_at", models.DateTimeField()),
                ("needs_reauth", models.BooleanField(default=False)),
                ("scopes", models.CharField(blank=True, max_length=1000)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("primary_locale", models.CharField(default="en", max_length=10)),
                ("iana_timezone", models.CharField(default="UTC", max_length=64)),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("ui_locale", models.CharField(default="en", max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("uninstalled", "Uninstalled"), ("frozen", "Frozen")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("uninstalled_at", models.DateTimeField(blank=True, null=True)),
                ("mosaiq_templates_ready", models.BooleanField(default=False)),
                (
                    "onboarding_step",
                    models.CharField(
                        choices=[
                            ("language", "Language"),
                            ("brand", "Brand"),
                            ("sources", "Sources"),
                            ("theme", "Theme"),
                            ("withdrawal", "Withdrawal"),
                            ("done", "Done"),
                        ],
                        default="language",
                        max_length=40,
                    ),
                ),
                ("import_apps", models.JSONField(blank=True, default=list)),
                ("ship_cutoff", models.JSONField(blank=True, null=True)),
                ("guarantee_policy", models.TextField(blank=True)),
                ("stock_threshold", models.PositiveSmallIntegerField(default=5)),
                ("ai_label_default", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-installed_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("actor", models.CharField(help_text="merchant, system, support", max_length=20)),
                ("action", models.CharField(max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
