# Generated by Django 5.2.17 on 2026-09-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="access_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="refresh_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
