# Generated by Django 5.2.17 on 2026-09-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_shop_access_token_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="installation_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
