# Generated by Django 5.2.17 on 2026-10-02 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_installation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, help_text='Defaults to BrandKit.brand_name', max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2, uppercase', max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company_reg_no', models.CharField(blank=True, help_text='KvK / HRB / BCE', max_length=40)),
                ('vat_id', models.CharField(blank=True, help_text='Format checked against country prefix only', max_length=20)),
                ('return_address_same', models.BooleanField(default=True)),
                ('return_address', models.JSONField(blank=True, help_text='Same keys as the address fields when return_address_same is False', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='core.shop')),
            ],
        ),
    ]
