# Generated by Django 5.2.17 on 2026-10-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_businessdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='onboarding_route',
            field=models.CharField(blank=True, choices=[('', 'Not chosen'), ('existing', 'Existing brand'), ('zero', 'Start from zero')], default='', help_text='F15-1: route chosen at the onboarding brand step', max_length=16),
        ),
    ]
