# Generated by Django 5.2.17 on 2026-09-30 21:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_installation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("pdp", "PDP"),
                            ("landing", "Landing"),
                            ("advertorial", "Advertorial"),
                            ("listicle", "Listicle"),
                            ("home", "Home"),
                            ("about", "About"),
                        ],
                        default="pdp",
                        max_length=20,
                    ),
                ),
                (
                    "structure",
                    models.JSONField(
                        default=dict, help_text="Section order + display settings; NO product text/prices/images/claims"
                    ),
                ),
                (
                    "shared_with_account",
                    models.BooleanField(
                        default=False,
                        help_text="Available to other shops of the same Shopify organization (v1.2; MVP: own shop only)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="saved_templates", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
