# Generated by Django 5.2.17 on 2026-10-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedtemplate',
            name='page_type',
            field=models.CharField(choices=[('pdp', 'PDP'), ('landing', 'Landing'), ('advertorial', 'Advertorial'), ('listicle', 'Listicle'), ('home', 'Home'), ('about', 'About'), ('faq', 'FAQ'), ('shipping', 'Shipping'), ('returns', 'Returns')], default='pdp', max_length=20),
        ),
    ]
