"""Language detection — simple heuristic for nl/en/de.

See docs/specs/F03-copy.md criterion 4.
Uses word lists + common patterns. Production can swap in langdetect.
"""

from __future__ import annotations

# Common words per language
_COMMON_WORDS: dict[str, set[str]] = {
    "nl": {
        "de",
        "het",
        "een",
        "en",
        "van",
        "voor",
        "met",
        "op",
        "aan",
        "is",
        "zijn",
        "worden",
        "niet",
        "ook",
        "maar",
        "dat",
        "die",
        "dit",
        "als",
        "bij",
        "uit",
        "om",
        "naar",
        "over",
        "door",
        "tegen",
        "vanaf",
        "je",
        "jij",
        "hij",
        "zij",
        "wij",
        "jullie",
        "u",
        "hebben",
        "heeft",
        "had",
        "kunnen",
        "moeten",
        "zullen",
        "willen",
        "goed",
        "slecht",
        "groot",
        "klein",
        "nieuw",
        "oud",
        "hoog",
        "laag",
        "sneller",
        "beter",
        "meest",
        "veel",
        "weinig",
        "alle",
        "elke",
    },
    "en": {
        "the",
        "a",
        "an",
        "and",
        "or",
        "but",
        "if",
        "then",
        "else",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "shall",
        "should",
        "can",
        "could",
        "may",
        "might",
        "must",
        "to",
        "of",
        "in",
        "for",
        "on",
        "with",
        "at",
        "by",
        "from",
        "as",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "between",
        "out",
        "over",
        "this",
        "that",
        "these",
        "those",
        "it",
        "its",
        "he",
        "she",
        "they",
        "we",
        "you",
        "i",
        "me",
        "my",
        "your",
        "his",
        "her",
        "our",
        "their",
        "what",
        "which",
        "who",
        "whom",
        "when",
        "where",
        "why",
        "how",
        "all",
        "each",
        "every",
        "both",
        "few",
        "more",
        "most",
        "other",
        "some",
        "such",
        "no",
        "nor",
        "not",
        "only",
        "own",
        "same",
        "so",
        "than",
        "too",
        "very",
        "just",
        "because",
        "about",
        "also",
        "good",
        "bad",
        "great",
        "best",
        "better",
        "new",
        "old",
        "fast",
        "quick",
        "easy",
        "simple",
        "free",
        "buy",
        "shop",
        "product",
        "price",
        "quality",
        "service",
        "support",
        "help",
    },
    "de": {
        "der",
        "die",
        "das",
        "ein",
        "eine",
        "einer",
        "eines",
        "einem",
        "einen",
        "und",
        "oder",
        "aber",
        "wenn",
        "dann",
        "ist",
        "sind",
        "war",
        "waren",
        "sein",
        "hat",
        "haben",
        "hatten",
        "kann",
        "konnte",
        "muss",
        "müssen",
        "soll",
        "sollen",
        "will",
        "wollen",
        "werden",
        "wurde",
        "ich",
        "du",
        "er",
        "sie",
        "es",
        "wir",
        "ihr",
        "man",
        "mich",
        "dich",
        "sich",
        "mir",
        "dir",
        "ihm",
        "uns",
        "euch",
        "mein",
        "dein",
        "unser",
        "euer",
        "dies",
        "dieser",
        "diese",
        "dieses",
        "jener",
        "welcher",
        "welche",
        "welches",
        "gut",
        "schlecht",
        "besser",
        "am",
        "besten",
        "neu",
        "alt",
        "schnell",
        "langsam",
        "einfach",
        "kompliziert",
        "kostenlos",
        "kaufen",
        "shop",
        "produkt",
        "preis",
        "qualität",
        "service",
        "unterstützung",
        "hilfe",
        "nicht",
        "auch",
        "noch",
        "schon",
        "nur",
        "sehr",
        "viel",
        "wenig",
        "alle",
        "jede",
        "kein",
        "keine",
    },
}


def detect_language(text: str) -> str | None:
    """Detect language of text. Returns 'nl', 'en', 'de', or None."""
    if not text or not text.strip():
        return None

    words = text.lower().split()

    scores: dict[str, int] = {"nl": 0, "en": 0, "de": 0}
    for word in words:
        clean = word.strip(".,!?;:\"'()-")
        for lang, common_words in _COMMON_WORDS.items():
            if clean in common_words:
                scores[lang] += 1

    if all(s == 0 for s in scores.values()):
        return None

    # Return highest scoring language
    best = max(scores, key=lambda k: scores[k])
    return best if scores[best] > 0 else None
