# Generated by Django 5.2.17 on 2026-09-30 08:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_installation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceAttestation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("variant_gid", models.CharField(max_length=255)),
                ("lowest_price_30d", models.DecimalField(decimal_places=2, max_digits=12)),
                ("valid_until", models.DateTimeField()),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="price_attestations", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_until"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("variant_gid", models.CharField(max_length=255)),
                ("market_handle", models.CharField(default="primary", max_length=80)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                ("observed_at", models.DateTimeField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("install_snapshot", "Install snapshot"),
                            ("webhook", "Webhook"),
                            ("daily_snapshot", "Daily snapshot"),
                            ("merchant_attested", "Merchant attested"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="price_history", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "variant_gid", "market_handle", "observed_at"],
                        name="compliance__shop_id_7868bd_idx",
                    )
                ],
            },
        ),
    ]
