# Generated by Django 5.2.17 on 2026-09-30 21:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_add_price_history"),
        ("core", "0003_add_installation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "reference",
                    models.CharField(help_text="e.g. MQW-7F3K9Q — shown to the customer", max_length=20, unique=True),
                ),
                ("customer_name", models.CharField(max_length=200)),
                (
                    "order_identifier",
                    models.CharField(
                        help_text="Order number as entered (not validated against Shopify)", max_length=100
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("locale", models.CharField(default="en", max_length=5)),
                ("submitted_at", models.DateTimeField()),
                ("confirmation_sent_at", models.DateTimeField(blank=True, null=True)),
                ("merchant_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("submitted", "Submitted"), ("handled", "Handled")], default="submitted", max_length=20
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="withdrawal_requests", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
