# Generated by Django 5.2.17 on 2026-10-02 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_withdrawalrequest'),
        ('core', '0004_businessdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_gid', models.CharField(max_length=255)),
                ('ship_from_country', models.CharField(blank=True, max_length=2, null=True)),
                ('processing_days_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('processing_days_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transit_days', models.JSONField(blank=True, null=True)),
                ('shipping_cost', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_overrides', to='core.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop', 'product_gid'), name='unique_delivery_override_per_shop_product')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(choices=[('dsers', 'DSers'), ('cj', 'CJ Dropshipping'), ('zendrop', 'Zendrop'), ('autods', 'AutoDS'), ('printify', 'Printify'), ('printful', 'Printful'), ('manual', 'Manual'), ('other', 'Other')], max_length=20)),
                ('ship_from_country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('processing_days_min', models.PositiveSmallIntegerField()),
                ('processing_days_max', models.PositiveSmallIntegerField()),
                ('transit_days', models.JSONField(help_text='Per market: {"NL": [5, 9], "DE": [6, 10]}; each [min, max]')),
                ('shipping_cost', models.JSONField(blank=True, help_text='Per market: {"NL": {"amount": "4.95", "free_from": "40.00"}}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profiles', to='core.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop', 'source_app'), name='unique_delivery_profile_per_shop_source')],
            },
        ),
    ]
