# Generated by Django 5.2.17 on 2026-10-02 03:28

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_deliveryoverride_deliveryprofile'),
        ('core', '0004_businessdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_fee_pct', models.DecimalField(decimal_places=4, default=Decimal('0.029'), max_digits=5)),
                ('payment_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=6)),
                ('returns_allowance_pct', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5)),
                ('target_margin_pct', models.DecimalField(decimal_places=4, default=Decimal('0.30'), max_digits=5)),
                ('price_ending', models.CharField(choices=[('95', '.95'), ('99', '.99'), ('00', '.00')], default='95', max_length=2)),
                ('markets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_settings', to='core.shop')),
            ],
        ),
    ]
