# Generated by Django 5.2.17 on 2026-10-02 04:28

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.compliance.models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_pricingsettings'),
        ('core', '0004_businessdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsettings',
            name='markets',
            field=models.JSONField(blank=True, default=apps.compliance.models._default_markets),
        ),
        migrations.CreateModel(
            name='PriceAdvice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_gid', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=80)),
                ('inputs', models.JSONField(default=dict)),
                ('advice', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_advices', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'product_gid'], name='compliance__shop_id_565f51_idx')],
            },
        ),
    ]
