# Generated by Django 5.2.17 on 2026-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("webhook_id", models.CharField(max_length=100, unique=True)),
                ("topic", models.CharField(max_length=80)),
                ("shop_domain", models.CharField(max_length=255)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(fields=["webhook_id"], name="ix_webhook_receipt_id"),
                    models.Index(fields=["processed", "received_at"], name="ix_webhook_receipt_proc"),
                ],
            },
        ),
    ]
