# Generated by Django 5.2.17 on 2026-09-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookreceipt",
            name="body_json",
            field=models.JSONField(blank=True, help_text="Parsed webhook body", null=True),
        ),
    ]
