# Generated by Django 5.2.17 on 2026-09-30 15:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_installation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("product_gid", models.CharField(max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("dsers", "DSers"),
                            ("cj", "CJ Dropshipping"),
                            ("zendrop", "Zendrop"),
                            ("autods", "AutoDS"),
                            ("printify", "Printify"),
                            ("printful", "Printful"),
                            ("unknown_app", "Unknown app"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "detected_by",
                    models.CharField(
                        choices=[
                            ("mosaiq", "Created by Mosaiq"),
                            ("fulfillment_location", "Fulfillment location"),
                            ("onboarding", "Onboarding answer"),
                            ("vendor", "Vendor field"),
                            ("sku", "SKU pattern"),
                            ("merchant", "Merchant confirmed"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "created_by_mosaiq",
                    models.BooleanField(
                        default=False,
                        help_text="Only True after product_create_manual; sole condition for full write access",
                    ),
                ),
                ("locked_fields", models.JSONField(default=list, help_text="List of field names Mosaiq never writes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="product_sources", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["shop", "product_gid"], name="sources_pro_shop_id_0e926d_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("shop", "product_gid"), name="unique_product_source_per_shop")
                ],
            },
        ),
    ]
