# Generated by Django 5.2.17 on 2026-10-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(max_length=300)),
                ('referrer_host', models.CharField(blank=True, default='', max_length=200)),
                ('lang', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'indexes': [models.Index(fields=['path', 'created_at'], name='marketing_m_path_12c3ff_idx')],
            },
        ),
    ]
