# Generated by Django 5.2.17 on 2026-10-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('shop_domain', models.CharField(blank=True, default='', max_length=200)),
                ('lang', models.CharField(default='en', max_length=5)),
                ('consent_text', models.TextField(blank=True, default='')),
                ('confirm_token', models.CharField(max_length=64, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
