# Generated by Django 5.2.17 on 2026-10-03 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='UninstallFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('shop_domain', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(choices=[('too_expensive', 'Too expensive'), ('not_useful', 'Not useful / missing features'), ('too_complex', 'Too complex'), ('switched', 'Switched to another tool'), ('closed_shop', 'Closed the shop'), ('other', 'Other')], max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('lang', models.CharField(default='en', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_emails', to='marketing.lead')),
            ],
            options={
                'unique_together': {('lead', 'step')},
            },
        ),
    ]
