# Generated by Django 5.2.17 on 2026-09-30 15:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_installation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandKit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("brand_name", models.CharField(max_length=80)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("warm", "Warm"),
                            ("premium", "Premium"),
                            ("playful", "Playful"),
                            ("clinical", "Clinical"),
                            ("sporty", "Sporty"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "palette",
                    models.JSONField(
                        help_text='{"primary":"#RRGGBB","secondary":...,"accent":...,"background":...,"text":...}'
                    ),
                ),
                (
                    "font_heading",
                    models.CharField(
                        blank=True, help_text="Key from bundled font list; empty = inherit theme font", max_length=40
                    ),
                ),
                (
                    "font_body",
                    models.CharField(
                        blank=True, help_text="Key from bundled font list; empty = inherit theme font", max_length=40
                    ),
                ),
                (
                    "style_preset",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("bold", "Bold"),
                            ("organic", "Organic"),
                            ("luxe", "Luxe"),
                            ("tech", "Tech"),
                            ("soft", "Soft"),
                        ],
                        max_length=20,
                    ),
                ),
                ("logo_file_gid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tokens_synced_at",
                    models.DateTimeField(blank=True, help_text="Last metafieldsSet of the design tokens", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="brandkit", to="core.shop"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
