# Generated by Django 5.2.17 on 2026-10-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_add_brandkit'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandkit',
            name='tagline',
            field=models.CharField(blank=True, help_text='Brand tagline from the niche_brand proposal (F15-5)', max_length=60),
        ),
    ]
