name: Lighthouse
on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: treosh/lighthouse-ci-action@v11
        with:
          configPath: .lighthouserc.json
